
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace RC.ML.PricePredict.Console
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                CPU = @"i5",
                GHz = 1.8F,
                GPU = @"intel",
                RAM = 4F,
                RAMType = @"ddr3",
                Screen = 13.3F,
                Storage = 128F,
                SSD = true,
                Weight = 1.4F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            //Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


            //Console.WriteLine($"CPU: {@"i5"}");
            //Console.WriteLine($"GHz: {1.8F}");
            //Console.WriteLine($"GPU: {@"intel"}");
            //Console.WriteLine($"RAM: {4F}");
            //Console.WriteLine($"RAMType: {@"ddr3"}");
            //Console.WriteLine($"Screen: {13.3F}");
            //Console.WriteLine($"Storage: {128F}");
            //Console.WriteLine($"SSD: {true}");
            //Console.WriteLine($"Weight: {1.4F}");
            //Console.WriteLine($"Price: {527F}");


            //Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            //Console.WriteLine("=============== End of process, hit any key to finish ===============");
            //Console.ReadKey();
        }
    }
}
